version: '3'
services:
  postgres:
    container_name: 'generic_erc721_mint_page_postgres'
    image: 'postgres:latest'
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT_INSIDE_CONTAINER}"
    command:
      - "-p $POSTGRES_PORT_INSIDE_CONTAINER"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  server:
    container_name: 'generic_erc721_mint_page_server'
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    depends_on:
      - postgres
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    environment:
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=$POSTGRES_DB
      - DB_PORT=$POSTGRES_PORT_INSIDE_CONTAINER
      - AUTHENTICATION_AUTH_SECRET=$AUTHENTICATION_AUTH_SECRET
      - SMART_CONTRACT_TOKENS_NB=$SMART_CONTRACT_TOKENS_NB
      - SMART_CONTRACT_IS_REVEALED=$SMART_CONTRACT_IS_REVEALED
    links:
      - postgres
  client:
    container_name: 'generic_erc721_mint_page_client'
    stdin_open: true
    depends_on:
      - server
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    environment:
      - REACT_APP_SMART_CONTRACT_NFT=$SMART_CONTRACT_ADDRESS
      - REACT_APP_TOKEN_PRICE_IN_ETH_NFT=$SMART_CONTRACT_TOKEN_PRICE_IN_ETH_NFT
      - REACT_APP_UNREVEALED_TOKEN_URI_NFT=$SMART_CONTRACT_UNREVEALED_TOKEN_URI_NFT
      - REACT_APP_UNREVEALED_TOKEN_SIGNATURE_NFT=$SMART_CONTRACT_UNREVEALED_TOKEN_SIGNATURE_NFT
      - REACT_APP_IPFS_GATEWAY_URL=$IPFS_GATEWAY_URL
    links:
      - server
    volumes:
      - /usr/src/app/node_modules
      - ./client:/user/src/app
  nginx:
    container_name: 'generic_erc721_mint_page_nginx'
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
volumes:
  postgres:
    driver: local